components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 4
    fs-task-processor:
      worker_threads: 1

  default_task_processor: main-task-processor

  components:
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stdout'
          level: info
          overflow_behavior: discard

    tracer:
      service-name: bsf_prototype

    server:
      listener:
        address: 0.0.0.0
        port: 8080
        task_processor: main-task-processor

    pcf-binding-service: {}
    pcf-binding-handler:
      path: /nbsf-management/v1/PcfBindings
      method: POST
      task_processor: main-task-processor
