/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/MbsExtProblemDetails.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



MbsExtProblemDetails::MbsExtProblemDetails()
{
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_Status = 0;
    m_StatusIsSet = false;
    m_Detail = utility::conversions::to_string_t("");
    m_DetailIsSet = false;
    m_Instance = utility::conversions::to_string_t("");
    m_InstanceIsSet = false;
    m_Cause = utility::conversions::to_string_t("");
    m_CauseIsSet = false;
    m_InvalidParamsIsSet = false;
    m_SupportedFeatures = utility::conversions::to_string_t("");
    m_SupportedFeaturesIsSet = false;
    m_AccessTokenErrorIsSet = false;
    m_AccessTokenRequestIsSet = false;
    m_NrfId = utility::conversions::to_string_t("");
    m_NrfIdIsSet = false;
    m_PcfFqdn = utility::conversions::to_string_t("");
    m_PcfFqdnIsSet = false;
    m_PcfIpEndPointsIsSet = false;
}

MbsExtProblemDetails::~MbsExtProblemDetails()
{
}

void MbsExtProblemDetails::validate()
{
    // TODO: implement validation
}

web::json::value MbsExtProblemDetails::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TypeIsSet)
    {
        val[utility::conversions::to_string_t(U("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_TitleIsSet)
    {
        val[utility::conversions::to_string_t(U("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_StatusIsSet)
    {
        val[utility::conversions::to_string_t(U("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_DetailIsSet)
    {
        val[utility::conversions::to_string_t(U("detail"))] = ModelBase::toJson(m_Detail);
    }
    if(m_InstanceIsSet)
    {
        val[utility::conversions::to_string_t(U("instance"))] = ModelBase::toJson(m_Instance);
    }
    if(m_CauseIsSet)
    {
        val[utility::conversions::to_string_t(U("cause"))] = ModelBase::toJson(m_Cause);
    }
    if(m_InvalidParamsIsSet)
    {
        val[utility::conversions::to_string_t(U("invalidParams"))] = ModelBase::toJson(m_InvalidParams);
    }
    if(m_SupportedFeaturesIsSet)
    {
        val[utility::conversions::to_string_t(U("supportedFeatures"))] = ModelBase::toJson(m_SupportedFeatures);
    }
    if(m_AccessTokenErrorIsSet)
    {
        val[utility::conversions::to_string_t(U("accessTokenError"))] = ModelBase::toJson(m_AccessTokenError);
    }
    if(m_AccessTokenRequestIsSet)
    {
        val[utility::conversions::to_string_t(U("accessTokenRequest"))] = ModelBase::toJson(m_AccessTokenRequest);
    }
    if(m_NrfIdIsSet)
    {
        val[utility::conversions::to_string_t(U("nrfId"))] = ModelBase::toJson(m_NrfId);
    }
    if(m_PcfFqdnIsSet)
    {
        val[utility::conversions::to_string_t(U("pcfFqdn"))] = ModelBase::toJson(m_PcfFqdn);
    }
    if(m_PcfIpEndPointsIsSet)
    {
        val[utility::conversions::to_string_t(U("pcfIpEndPoints"))] = ModelBase::toJson(m_PcfIpEndPoints);
    }

    return val;
}

bool MbsExtProblemDetails::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("status")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("detail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("detail")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDetail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDetail);
            setDetail(refVal_setDetail);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("instance"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("instance")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInstance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInstance);
            setInstance(refVal_setInstance);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("cause"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("cause")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCause;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCause);
            setCause(refVal_setCause);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("invalidParams"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("invalidParams")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<InvalidParam>> refVal_setInvalidParams;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInvalidParams);
            setInvalidParams(refVal_setInvalidParams);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("supportedFeatures"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("supportedFeatures")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSupportedFeatures;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSupportedFeatures);
            setSupportedFeatures(refVal_setSupportedFeatures);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("accessTokenError"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("accessTokenError")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AccessTokenErr> refVal_setAccessTokenError;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccessTokenError);
            setAccessTokenError(refVal_setAccessTokenError);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("accessTokenRequest"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("accessTokenRequest")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AccessTokenReq> refVal_setAccessTokenRequest;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccessTokenRequest);
            setAccessTokenRequest(refVal_setAccessTokenRequest);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("nrfId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("nrfId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNrfId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNrfId);
            setNrfId(refVal_setNrfId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("pcfFqdn"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("pcfFqdn")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPcfFqdn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPcfFqdn);
            setPcfFqdn(refVal_setPcfFqdn);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("pcfIpEndPoints"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("pcfIpEndPoints")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<IpEndPoint>> refVal_setPcfIpEndPoints;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPcfIpEndPoints);
            setPcfIpEndPoints(refVal_setPcfIpEndPoints);
        }
    }
    return ok;
}

void MbsExtProblemDetails::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("type")), m_Type));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("title")), m_Title));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("status")), m_Status));
    }
    if(m_DetailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("detail")), m_Detail));
    }
    if(m_InstanceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("instance")), m_Instance));
    }
    if(m_CauseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("cause")), m_Cause));
    }
    if(m_InvalidParamsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("invalidParams")), m_InvalidParams));
    }
    if(m_SupportedFeaturesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("supportedFeatures")), m_SupportedFeatures));
    }
    if(m_AccessTokenErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("accessTokenError")), m_AccessTokenError));
    }
    if(m_AccessTokenRequestIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("accessTokenRequest")), m_AccessTokenRequest));
    }
    if(m_NrfIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("nrfId")), m_NrfId));
    }
    if(m_PcfFqdnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("pcfFqdn")), m_PcfFqdn));
    }
    if(m_PcfIpEndPointsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("pcfIpEndPoints")), m_PcfIpEndPoints));
    }
}

bool MbsExtProblemDetails::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("status"))))
    {
        int32_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("detail"))))
    {
        utility::string_t refVal_setDetail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("detail"))), refVal_setDetail );
        setDetail(refVal_setDetail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("instance"))))
    {
        utility::string_t refVal_setInstance;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("instance"))), refVal_setInstance );
        setInstance(refVal_setInstance);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("cause"))))
    {
        utility::string_t refVal_setCause;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("cause"))), refVal_setCause );
        setCause(refVal_setCause);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("invalidParams"))))
    {
        std::vector<std::shared_ptr<InvalidParam>> refVal_setInvalidParams;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("invalidParams"))), refVal_setInvalidParams );
        setInvalidParams(refVal_setInvalidParams);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("supportedFeatures"))))
    {
        utility::string_t refVal_setSupportedFeatures;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("supportedFeatures"))), refVal_setSupportedFeatures );
        setSupportedFeatures(refVal_setSupportedFeatures);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("accessTokenError"))))
    {
        std::shared_ptr<AccessTokenErr> refVal_setAccessTokenError;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("accessTokenError"))), refVal_setAccessTokenError );
        setAccessTokenError(refVal_setAccessTokenError);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("accessTokenRequest"))))
    {
        std::shared_ptr<AccessTokenReq> refVal_setAccessTokenRequest;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("accessTokenRequest"))), refVal_setAccessTokenRequest );
        setAccessTokenRequest(refVal_setAccessTokenRequest);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("nrfId"))))
    {
        utility::string_t refVal_setNrfId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("nrfId"))), refVal_setNrfId );
        setNrfId(refVal_setNrfId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("pcfFqdn"))))
    {
        utility::string_t refVal_setPcfFqdn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("pcfFqdn"))), refVal_setPcfFqdn );
        setPcfFqdn(refVal_setPcfFqdn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("pcfIpEndPoints"))))
    {
        std::vector<std::shared_ptr<IpEndPoint>> refVal_setPcfIpEndPoints;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("pcfIpEndPoints"))), refVal_setPcfIpEndPoints );
        setPcfIpEndPoints(refVal_setPcfIpEndPoints);
    }
    return ok;
}

utility::string_t MbsExtProblemDetails::getType() const
{
    return m_Type;
}

void MbsExtProblemDetails::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool MbsExtProblemDetails::typeIsSet() const
{
    return m_TypeIsSet;
}

void MbsExtProblemDetails::unsetType()
{
    m_TypeIsSet = false;
}
utility::string_t MbsExtProblemDetails::getTitle() const
{
    return m_Title;
}

void MbsExtProblemDetails::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool MbsExtProblemDetails::titleIsSet() const
{
    return m_TitleIsSet;
}

void MbsExtProblemDetails::unsetTitle()
{
    m_TitleIsSet = false;
}
int32_t MbsExtProblemDetails::getStatus() const
{
    return m_Status;
}

void MbsExtProblemDetails::setStatus(int32_t value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool MbsExtProblemDetails::statusIsSet() const
{
    return m_StatusIsSet;
}

void MbsExtProblemDetails::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t MbsExtProblemDetails::getDetail() const
{
    return m_Detail;
}

void MbsExtProblemDetails::setDetail(const utility::string_t& value)
{
    m_Detail = value;
    m_DetailIsSet = true;
}

bool MbsExtProblemDetails::detailIsSet() const
{
    return m_DetailIsSet;
}

void MbsExtProblemDetails::unsetDetail()
{
    m_DetailIsSet = false;
}
utility::string_t MbsExtProblemDetails::getInstance() const
{
    return m_Instance;
}

void MbsExtProblemDetails::setInstance(const utility::string_t& value)
{
    m_Instance = value;
    m_InstanceIsSet = true;
}

bool MbsExtProblemDetails::instanceIsSet() const
{
    return m_InstanceIsSet;
}

void MbsExtProblemDetails::unsetInstance()
{
    m_InstanceIsSet = false;
}
utility::string_t MbsExtProblemDetails::getCause() const
{
    return m_Cause;
}

void MbsExtProblemDetails::setCause(const utility::string_t& value)
{
    m_Cause = value;
    m_CauseIsSet = true;
}

bool MbsExtProblemDetails::causeIsSet() const
{
    return m_CauseIsSet;
}

void MbsExtProblemDetails::unsetCause()
{
    m_CauseIsSet = false;
}
std::vector<std::shared_ptr<InvalidParam>>& MbsExtProblemDetails::getInvalidParams()
{
    return m_InvalidParams;
}

void MbsExtProblemDetails::setInvalidParams(const std::vector<std::shared_ptr<InvalidParam>>& value)
{
    m_InvalidParams = value;
    m_InvalidParamsIsSet = true;
}

bool MbsExtProblemDetails::invalidParamsIsSet() const
{
    return m_InvalidParamsIsSet;
}

void MbsExtProblemDetails::unsetInvalidParams()
{
    m_InvalidParamsIsSet = false;
}
utility::string_t MbsExtProblemDetails::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}

void MbsExtProblemDetails::setSupportedFeatures(const utility::string_t& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}

bool MbsExtProblemDetails::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}

void MbsExtProblemDetails::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}
std::shared_ptr<AccessTokenErr> MbsExtProblemDetails::getAccessTokenError() const
{
    return m_AccessTokenError;
}

void MbsExtProblemDetails::setAccessTokenError(const std::shared_ptr<AccessTokenErr>& value)
{
    m_AccessTokenError = value;
    m_AccessTokenErrorIsSet = true;
}

bool MbsExtProblemDetails::accessTokenErrorIsSet() const
{
    return m_AccessTokenErrorIsSet;
}

void MbsExtProblemDetails::unsetAccessTokenError()
{
    m_AccessTokenErrorIsSet = false;
}
std::shared_ptr<AccessTokenReq> MbsExtProblemDetails::getAccessTokenRequest() const
{
    return m_AccessTokenRequest;
}

void MbsExtProblemDetails::setAccessTokenRequest(const std::shared_ptr<AccessTokenReq>& value)
{
    m_AccessTokenRequest = value;
    m_AccessTokenRequestIsSet = true;
}

bool MbsExtProblemDetails::accessTokenRequestIsSet() const
{
    return m_AccessTokenRequestIsSet;
}

void MbsExtProblemDetails::unsetAccessTokenRequest()
{
    m_AccessTokenRequestIsSet = false;
}
utility::string_t MbsExtProblemDetails::getNrfId() const
{
    return m_NrfId;
}

void MbsExtProblemDetails::setNrfId(const utility::string_t& value)
{
    m_NrfId = value;
    m_NrfIdIsSet = true;
}

bool MbsExtProblemDetails::nrfIdIsSet() const
{
    return m_NrfIdIsSet;
}

void MbsExtProblemDetails::unsetNrfId()
{
    m_NrfIdIsSet = false;
}
utility::string_t MbsExtProblemDetails::getPcfFqdn() const
{
    return m_PcfFqdn;
}

void MbsExtProblemDetails::setPcfFqdn(const utility::string_t& value)
{
    m_PcfFqdn = value;
    m_PcfFqdnIsSet = true;
}

bool MbsExtProblemDetails::pcfFqdnIsSet() const
{
    return m_PcfFqdnIsSet;
}

void MbsExtProblemDetails::unsetPcfFqdn()
{
    m_PcfFqdnIsSet = false;
}
std::vector<std::shared_ptr<IpEndPoint>>& MbsExtProblemDetails::getPcfIpEndPoints()
{
    return m_PcfIpEndPoints;
}

void MbsExtProblemDetails::setPcfIpEndPoints(const std::vector<std::shared_ptr<IpEndPoint>>& value)
{
    m_PcfIpEndPoints = value;
    m_PcfIpEndPointsIsSet = true;
}

bool MbsExtProblemDetails::pcfIpEndPointsIsSet() const
{
    return m_PcfIpEndPointsIsSet;
}

void MbsExtProblemDetails::unsetPcfIpEndPoints()
{
    m_PcfIpEndPointsIsSet = false;
}
}
}
}
}


