/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SnssaiDnnPair.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



SnssaiDnnPair::SnssaiDnnPair()
{
    m_Dnn = utility::conversions::to_string_t("");
    m_DnnIsSet = false;
    m_SnssaiIsSet = false;
}

SnssaiDnnPair::~SnssaiDnnPair()
{
}

void SnssaiDnnPair::validate()
{
    // TODO: implement validation
}

web::json::value SnssaiDnnPair::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_DnnIsSet)
    {
        val[utility::conversions::to_string_t(U("dnn"))] = ModelBase::toJson(m_Dnn);
    }
    if(m_SnssaiIsSet)
    {
        val[utility::conversions::to_string_t(U("snssai"))] = ModelBase::toJson(m_Snssai);
    }

    return val;
}

bool SnssaiDnnPair::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("dnn"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("dnn")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDnn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDnn);
            setDnn(refVal_setDnn);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("snssai"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("snssai")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Snssai> refVal_setSnssai;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSnssai);
            setSnssai(refVal_setSnssai);
        }
    }
    return ok;
}

void SnssaiDnnPair::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_DnnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("dnn")), m_Dnn));
    }
    if(m_SnssaiIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("snssai")), m_Snssai));
    }
}

bool SnssaiDnnPair::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("dnn"))))
    {
        utility::string_t refVal_setDnn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("dnn"))), refVal_setDnn );
        setDnn(refVal_setDnn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("snssai"))))
    {
        std::shared_ptr<Snssai> refVal_setSnssai;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("snssai"))), refVal_setSnssai );
        setSnssai(refVal_setSnssai);
    }
    return ok;
}

utility::string_t SnssaiDnnPair::getDnn() const
{
    return m_Dnn;
}

void SnssaiDnnPair::setDnn(const utility::string_t& value)
{
    m_Dnn = value;
    m_DnnIsSet = true;
}

bool SnssaiDnnPair::dnnIsSet() const
{
    return m_DnnIsSet;
}

void SnssaiDnnPair::unsetDnn()
{
    m_DnnIsSet = false;
}
std::shared_ptr<Snssai> SnssaiDnnPair::getSnssai() const
{
    return m_Snssai;
}

void SnssaiDnnPair::setSnssai(const std::shared_ptr<Snssai>& value)
{
    m_Snssai = value;
    m_SnssaiIsSet = true;
}

bool SnssaiDnnPair::snssaiIsSet() const
{
    return m_SnssaiIsSet;
}

void SnssaiDnnPair::unsetSnssai()
{
    m_SnssaiIsSet = false;
}
}
}
}
}


