/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IndividualPCFForAUEBindingDocumentApi.h
 *
 * 
 */

#ifndef IndividualPCFForAUEBindingDocumentApi_H_
#define IndividualPCFForAUEBindingDocumentApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "PcfForUeBinding.h"
#include "PcfForUeBindingPatch.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  IndividualPCFForAUEBindingDocumentApiException: public std::exception
{
public:
    IndividualPCFForAUEBindingDocumentApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace IndividualPCFForAUEBindingDocumentApiResources {
/// <summary>
/// Delete an existing Individual PCF for a UE Binding information
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  Pcf_ue_bindingsBindingIdResource: public restbed::Resource
{
public:
    Pcf_ue_bindingsBindingIdResource(const std::string& context = "/nbsf-management/v1");
    virtual ~Pcf_ue_bindingsBindingIdResource() = default;

    Pcf_ue_bindingsBindingIdResource(
        const Pcf_ue_bindingsBindingIdResource& other) = default; // copy constructor
    Pcf_ue_bindingsBindingIdResource(Pcf_ue_bindingsBindingIdResource&& other) noexcept = default; // move constructor

    Pcf_ue_bindingsBindingIdResource& operator=(const Pcf_ue_bindingsBindingIdResource& other) = default; // copy assignment
    Pcf_ue_bindingsBindingIdResource& operator=(Pcf_ue_bindingsBindingIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<int(
        std::string & bindingId)> handler_DELETE_func =
            [](std::string &) -> int
                { throw IndividualPCFForAUEBindingDocumentApiException(501, "Not implemented"); };

    std::function<std::pair<int, PcfForUeBinding>(
        std::string & bindingId, PcfForUeBindingPatch & pcfForUeBindingPatch)> handler_PATCH_func =
            [](std::string &, PcfForUeBindingPatch &) -> std::pair<int, PcfForUeBinding>
                { throw IndividualPCFForAUEBindingDocumentApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual int handler_DELETE(
        std::string & bindingId);

    virtual std::pair<int, PcfForUeBinding> handler_PATCH(
        std::string & bindingId, PcfForUeBindingPatch & pcfForUeBindingPatch);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleIndividualPCFForAUEBindingDocumentApiException(const IndividualPCFForAUEBindingDocumentApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_DELETE_internal(const std::shared_ptr<restbed::Session> session);
    void handler_PATCH_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace IndividualPCFForAUEBindingDocumentApiResources */

using IndividualPCFForAUEBindingDocumentApiPcf_ue_bindingsBindingIdResource [[deprecated]] = IndividualPCFForAUEBindingDocumentApiResources::Pcf_ue_bindingsBindingIdResource;

//
// The restbed service to actually implement the REST server
//
class  IndividualPCFForAUEBindingDocumentApi
{
public:
    explicit IndividualPCFForAUEBindingDocumentApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~IndividualPCFForAUEBindingDocumentApi();

    std::shared_ptr<IndividualPCFForAUEBindingDocumentApiResources::Pcf_ue_bindingsBindingIdResource> getPcf_ue_bindingsBindingIdResource();

    void setResource(std::shared_ptr<IndividualPCFForAUEBindingDocumentApiResources::Pcf_ue_bindingsBindingIdResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setIndividualPCFForAUEBindingDocumentApiPcf_ue_bindingsBindingIdResource(std::shared_ptr<IndividualPCFForAUEBindingDocumentApiResources::Pcf_ue_bindingsBindingIdResource> spIndividualPCFForAUEBindingDocumentApiPcf_ue_bindingsBindingIdResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<IndividualPCFForAUEBindingDocumentApiResources::Pcf_ue_bindingsBindingIdResource> m_spPcf_ue_bindingsBindingIdResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* IndividualPCFForAUEBindingDocumentApi_H_ */

