/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IndividualPCFBindingDocumentApi.h
 *
 * 
 */

#ifndef IndividualPCFBindingDocumentApi_H_
#define IndividualPCFBindingDocumentApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  IndividualPCFBindingDocumentApiException: public std::exception
{
public:
    IndividualPCFBindingDocumentApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace IndividualPCFBindingDocumentApiResources {
/// <summary>
/// Delete an existing Individual PCF for a PDU Session Binding information
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  PcfBindingsBindingIdResource: public restbed::Resource
{
public:
    PcfBindingsBindingIdResource(const std::string& context = "/nbsf-management/v1");
    virtual ~PcfBindingsBindingIdResource() = default;

    PcfBindingsBindingIdResource(
        const PcfBindingsBindingIdResource& other) = default; // copy constructor
    PcfBindingsBindingIdResource(PcfBindingsBindingIdResource&& other) noexcept = default; // move constructor

    PcfBindingsBindingIdResource& operator=(const PcfBindingsBindingIdResource& other) = default; // copy assignment
    PcfBindingsBindingIdResource& operator=(PcfBindingsBindingIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<int(
        std::string & bindingId)> handler_DELETE_func =
            [](std::string &) -> int
                { throw IndividualPCFBindingDocumentApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual int handler_DELETE(
        std::string & bindingId);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleIndividualPCFBindingDocumentApiException(const IndividualPCFBindingDocumentApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_DELETE_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace IndividualPCFBindingDocumentApiResources */

using IndividualPCFBindingDocumentApiPcfBindingsBindingIdResource [[deprecated]] = IndividualPCFBindingDocumentApiResources::PcfBindingsBindingIdResource;

//
// The restbed service to actually implement the REST server
//
class  IndividualPCFBindingDocumentApi
{
public:
    explicit IndividualPCFBindingDocumentApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~IndividualPCFBindingDocumentApi();

    std::shared_ptr<IndividualPCFBindingDocumentApiResources::PcfBindingsBindingIdResource> getPcfBindingsBindingIdResource();

    void setResource(std::shared_ptr<IndividualPCFBindingDocumentApiResources::PcfBindingsBindingIdResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setIndividualPCFBindingDocumentApiPcfBindingsBindingIdResource(std::shared_ptr<IndividualPCFBindingDocumentApiResources::PcfBindingsBindingIdResource> spIndividualPCFBindingDocumentApiPcfBindingsBindingIdResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<IndividualPCFBindingDocumentApiResources::PcfBindingsBindingIdResource> m_spPcfBindingsBindingIdResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* IndividualPCFBindingDocumentApi_H_ */

