/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IndividualSubscriptionDocumentApi.h
 *
 * 
 */

#ifndef IndividualSubscriptionDocumentApi_H_
#define IndividualSubscriptionDocumentApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "BsfSubscription.h"
#include "BsfSubscriptionResp.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  IndividualSubscriptionDocumentApiException: public std::exception
{
public:
    IndividualSubscriptionDocumentApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace IndividualSubscriptionDocumentApiResources {
/// <summary>
/// Delete an individual subscription for event notifications from the BSF
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  SubscriptionsSubIdResource: public restbed::Resource
{
public:
    SubscriptionsSubIdResource(const std::string& context = "/nbsf-management/v1");
    virtual ~SubscriptionsSubIdResource() = default;

    SubscriptionsSubIdResource(
        const SubscriptionsSubIdResource& other) = default; // copy constructor
    SubscriptionsSubIdResource(SubscriptionsSubIdResource&& other) noexcept = default; // move constructor

    SubscriptionsSubIdResource& operator=(const SubscriptionsSubIdResource& other) = default; // copy assignment
    SubscriptionsSubIdResource& operator=(SubscriptionsSubIdResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<int(
        std::string & subId)> handler_DELETE_func =
            [](std::string &) -> int
                { throw IndividualSubscriptionDocumentApiException(501, "Not implemented"); };

    std::function<std::pair<int, BsfSubscriptionResp>(
        std::string & subId, BsfSubscription & bsfSubscription)> handler_PUT_func =
            [](std::string &, BsfSubscription &) -> std::pair<int, BsfSubscriptionResp>
                { throw IndividualSubscriptionDocumentApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual int handler_DELETE(
        std::string & subId);

    virtual std::pair<int, BsfSubscriptionResp> handler_PUT(
        std::string & subId, BsfSubscription & bsfSubscription);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleIndividualSubscriptionDocumentApiException(const IndividualSubscriptionDocumentApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_DELETE_internal(const std::shared_ptr<restbed::Session> session);
    void handler_PUT_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace IndividualSubscriptionDocumentApiResources */

using IndividualSubscriptionDocumentApiSubscriptionsSubIdResource [[deprecated]] = IndividualSubscriptionDocumentApiResources::SubscriptionsSubIdResource;

//
// The restbed service to actually implement the REST server
//
class  IndividualSubscriptionDocumentApi
{
public:
    explicit IndividualSubscriptionDocumentApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~IndividualSubscriptionDocumentApi();

    std::shared_ptr<IndividualSubscriptionDocumentApiResources::SubscriptionsSubIdResource> getSubscriptionsSubIdResource();

    void setResource(std::shared_ptr<IndividualSubscriptionDocumentApiResources::SubscriptionsSubIdResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setIndividualSubscriptionDocumentApiSubscriptionsSubIdResource(std::shared_ptr<IndividualSubscriptionDocumentApiResources::SubscriptionsSubIdResource> spIndividualSubscriptionDocumentApiSubscriptionsSubIdResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<IndividualSubscriptionDocumentApiResources::SubscriptionsSubIdResource> m_spSubscriptionsSubIdResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* IndividualSubscriptionDocumentApi_H_ */

