/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PCFBindingsCollectionApi.h
 *
 * 
 */

#ifndef PCFBindingsCollectionApi_H_
#define PCFBindingsCollectionApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "ExtProblemDetails.h"
#include "Ipv6Prefix.h"
#include "PcfBinding.h"
#include "ProblemDetails.h"
#include "Snssai.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  PCFBindingsCollectionApiException: public std::exception
{
public:
    PCFBindingsCollectionApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace PCFBindingsCollectionApiResources {
/// <summary>
/// Create a new Individual PCF for a PDU Session binding information
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  PcfBindingsResource: public restbed::Resource
{
public:
    PcfBindingsResource(const std::string& context = "/nbsf-management/v1");
    virtual ~PcfBindingsResource() = default;

    PcfBindingsResource(
        const PcfBindingsResource& other) = default; // copy constructor
    PcfBindingsResource(PcfBindingsResource&& other) noexcept = default; // move constructor

    PcfBindingsResource& operator=(const PcfBindingsResource& other) = default; // copy assignment
    PcfBindingsResource& operator=(PcfBindingsResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, PcfBinding>(
        PcfBinding & pcfBinding)> handler_POST_func =
            [](PcfBinding &) -> std::pair<int, PcfBinding>
                { throw PCFBindingsCollectionApiException(501, "Not implemented"); };

    std::function<std::pair<int, PcfBinding>(
        std::string & ipv4Addr, Ipv6Prefix & ipv6Prefix, std::string & macAddr48, std::string & dnn, std::string & supi, std::string & gpsi, Snssai & snssai, std::string & ipDomain, std::string & suppFeat)> handler_GET_func =
            [](std::string &, Ipv6Prefix &, std::string &, std::string &, std::string &, std::string &, Snssai &, std::string &, std::string &) -> std::pair<int, PcfBinding>
                { throw PCFBindingsCollectionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, PcfBinding> handler_POST(
        PcfBinding & pcfBinding);

    virtual std::pair<int, PcfBinding> handler_GET(
        std::string & ipv4Addr, Ipv6Prefix & ipv6Prefix, std::string & macAddr48, std::string & dnn, std::string & supi, std::string & gpsi, Snssai & snssai, std::string & ipDomain, std::string & suppFeat);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handlePCFBindingsCollectionApiException(const PCFBindingsCollectionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_POST_internal(const std::shared_ptr<restbed::Session> session);
    void handler_GET_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace PCFBindingsCollectionApiResources */

using PCFBindingsCollectionApiPcfBindingsResource [[deprecated]] = PCFBindingsCollectionApiResources::PcfBindingsResource;

//
// The restbed service to actually implement the REST server
//
class  PCFBindingsCollectionApi
{
public:
    explicit PCFBindingsCollectionApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~PCFBindingsCollectionApi();

    std::shared_ptr<PCFBindingsCollectionApiResources::PcfBindingsResource> getPcfBindingsResource();

    void setResource(std::shared_ptr<PCFBindingsCollectionApiResources::PcfBindingsResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setPCFBindingsCollectionApiPcfBindingsResource(std::shared_ptr<PCFBindingsCollectionApiResources::PcfBindingsResource> spPCFBindingsCollectionApiPcfBindingsResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<PCFBindingsCollectionApiResources::PcfBindingsResource> m_spPcfBindingsResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* PCFBindingsCollectionApi_H_ */

