/**
 * Nbsf_Management
 * Binding Support Management Service API.    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).    All rights reserved.  
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.7.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SubscriptionsCollectionApi.h
 *
 * 
 */

#ifndef SubscriptionsCollectionApi_H_
#define SubscriptionsCollectionApi_H_


#include <memory>
#include <utility>
#include <exception>
#include <functional>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/request.hpp>
#include <corvusoft/restbed/service.hpp>
#include <corvusoft/restbed/settings.hpp>

#include "BsfSubscription.h"
#include "BsfSubscriptionResp.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

///
/// Exception to flag problems in the handlers
///
class  SubscriptionsCollectionApiException: public std::exception
{
public:
    SubscriptionsCollectionApiException(int status_code, std::string what);

    int getStatus() const;
    const char* what() const noexcept override;

private:
    int m_status;
    std::string m_what;
};

namespace SubscriptionsCollectionApiResources {
/// <summary>
/// Create an individual subscription for event notifications from the BSF
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  SubscriptionsResource: public restbed::Resource
{
public:
    SubscriptionsResource(const std::string& context = "/nbsf-management/v1");
    virtual ~SubscriptionsResource() = default;

    SubscriptionsResource(
        const SubscriptionsResource& other) = default; // copy constructor
    SubscriptionsResource(SubscriptionsResource&& other) noexcept = default; // move constructor

    SubscriptionsResource& operator=(const SubscriptionsResource& other) = default; // copy assignment
    SubscriptionsResource& operator=(SubscriptionsResource&& other) noexcept = default; // move assignment

    /////////////////////////////////////////////////////
    // Set these to implement the server functionality //
    /////////////////////////////////////////////////////
    std::function<std::pair<int, BsfSubscriptionResp>(
        BsfSubscription & bsfSubscription)> handler_POST_func =
            [](BsfSubscription &) -> std::pair<int, BsfSubscriptionResp>
                { throw SubscriptionsCollectionApiException(501, "Not implemented"); };


protected:
    //////////////////////////////////////////////////////////
    // As an alternative to setting the `std::function`s    //
    // override these to implement the server functionality //
    //////////////////////////////////////////////////////////

    virtual std::pair<int, BsfSubscriptionResp> handler_POST(
        BsfSubscription & bsfSubscription);


protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual std::string extractBodyContent(const std::shared_ptr<restbed::Session>& session);
    virtual std::string extractFormParamsFromBody(const std::string& paramName, const std::string& body);

    virtual std::pair<int, std::string> handleSubscriptionsCollectionApiException(const SubscriptionsCollectionApiException& e);
    virtual std::pair<int, std::string> handleStdException(const std::exception& e);
    virtual std::pair<int, std::string> handleUnspecifiedException();

    virtual void setResponseHeader(const std::shared_ptr<restbed::Session>& session,
        const std::string& header);

    virtual void returnResponse(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result, std::multimap<std::string, std::string>& contentType);
    virtual void defaultSessionClose(const std::shared_ptr<restbed::Session>& session,
        const int status, const std::string& result);

private:
    void handler_POST_internal(const std::shared_ptr<restbed::Session> session);
};

} /* namespace SubscriptionsCollectionApiResources */

using SubscriptionsCollectionApiSubscriptionsResource [[deprecated]] = SubscriptionsCollectionApiResources::SubscriptionsResource;

//
// The restbed service to actually implement the REST server
//
class  SubscriptionsCollectionApi
{
public:
    explicit SubscriptionsCollectionApi(std::shared_ptr<restbed::Service> const& restbedService);
    virtual ~SubscriptionsCollectionApi();

    std::shared_ptr<SubscriptionsCollectionApiResources::SubscriptionsResource> getSubscriptionsResource();

    void setResource(std::shared_ptr<SubscriptionsCollectionApiResources::SubscriptionsResource> resource);
    [[deprecated("use setResource()")]]
    virtual void setSubscriptionsCollectionApiSubscriptionsResource(std::shared_ptr<SubscriptionsCollectionApiResources::SubscriptionsResource> spSubscriptionsCollectionApiSubscriptionsResource);

    virtual void publishDefaultResources();

    virtual std::shared_ptr<restbed::Service> service();

protected:
    std::shared_ptr<SubscriptionsCollectionApiResources::SubscriptionsResource> m_spSubscriptionsResource;

private:
    std::shared_ptr<restbed::Service> m_service;
};


}
}
}
}

#endif /* SubscriptionsCollectionApi_H_ */

